version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t nisha26/stockpriceapp:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker login -u nisha26 -p Nisha@261220
      - docker push nisha26/stockpriceapp:latest
