version: 0.2

phases:
 build:
  commands:
     - docker build -t 597052231981.dkr.ecr.ap-south-1.amazonaws.com/stock_registry/stocksprice:latest .
     - docker push 597052231981.dkr.ecr.ap-south-1.amazonaws.com/stock_regstry/stocksprice:latest
 post_build:
   commands:
     -echo Build completed
artifacts:
  files:
    -'**/*'


