version: 0.2

phases:
 build:
  commands:
     - docker build -t nisha26/stocksprice:latest .
     - docker push 597052231981.dkr.ecr.ap-south-1.amazonaws.com/stocksprice:latest
 post_build:
   commands:
     -echo Build completed
artifacts:
  files:
    -'**/*'


