version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - docker build -t 597052231981.dkr.ecr.ap-south-1.amazonaws.com/stocksprice:latest .
      - docker push 597052231981.dkr.ecr.ap-south-1.amazonaws.com/stocksprice:latest
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'


