spring:
   datasource:
      url: jdbc:mysql://stockpricedb.cws9ymtyrwdv.ap-south-1.rds.amazonaws.com/stockpricedb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root1234
   jpa:
      hibernate.ddl-auto: update     
server:
  port: 7001    

